apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

final Properties env = new Properties()

def envFile = file("${rootDir}/env.properties")

if (envFile.exists()) {
    envFile.withInputStream {
        env.load(it)
    }
} else {
    println("WARNING: env.properties não encontrado. Usando valores padrão.")
}

android {

    namespace 'juniojsv.mtk.easy.su'

    compileSdk 36

    defaultConfig {
        applicationId 'juniojsv.mtk.easy.su'

        minSdkVersion 23
        targetSdkVersion 36

        versionCode 211
        versionName "2.2.2"
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "mtk-easy-su-v${defaultConfig.versionName}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildTypes {

        debug {
            resValue "string",
                    "application_advertising_id",
                    env.getProperty(
                            "application.advertising.id",
                            "ca-app-pub-3940256099942544/1033173712"
                    )

            resValue "string",
                    "interstitial_advertising_id",
                    env.getProperty(
                            "interstitial.advertising.id",
                            "ca-app-pub-3940256099942544/1033173712"
                    )

            resValue "string",
                    "banner_advertising_id",
                    env.getProperty(
                            "banner.advertising.id",
                            "ca-app-pub-3940256099942544/6300978111"
                    )

            resValue "string",
                    "admob_test_device",
                    env.getProperty(
                            "admob.test.device",
                            ""
                    )
        }

        release {
            minifyEnabled true
            shrinkResources true

            proguardFiles(
                    getDefaultProguardFile(
                            'proguard-android-optimize.txt'
                    ),
                    'proguard-rules.pro'
            )
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {

    implementation fileTree(
            dir: 'libs',
            include: ['*.jar']
    )

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    implementation 'androidx.core:core-ktx:1.16.0'

    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.google.android.gms:play-services-ads:24.1.0'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'

    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
}
